// <auto-generated />
using System;
using EF_Prac.RelationShips;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SmartDataTest2.Migrations.EF_RelationsDB
{
    [DbContext(typeof(EF_RelationsDBContext))]
    partial class EF_RelationsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_Prac.RelationShips.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<bool?>("AvailCanteenService")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfficeFloorId")
                        .HasColumnType("int");

                    b.Property<string>("Tech")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("OfficeFloorId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EF_Prac.RelationShips.Models.OfficeFloor", b =>
                {
                    b.Property<int>("FloorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FloorId"));

                    b.Property<string>("Floor_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FloorId");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("EF_Prac.RelationShips.Models.SystemDetail", b =>
                {
                    b.Property<int>("SysDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SysDetailId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("SystemIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemOS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SysDetailId");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("SystemDetails");
                });

            modelBuilder.Entity("EF_Prac.RelationShips.Models.Employee", b =>
                {
                    b.HasOne("EF_Prac.RelationShips.Models.OfficeFloor", "OfficeFloor")
                        .WithMany("Employees")
                        .HasForeignKey("OfficeFloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfficeFloor");
                });

            modelBuilder.Entity("EF_Prac.RelationShips.Models.SystemDetail", b =>
                {
                    b.HasOne("EF_Prac.RelationShips.Models.Employee", "Employee")
                        .WithOne("SystemDetail")
                        .HasForeignKey("EF_Prac.RelationShips.Models.SystemDetail", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EF_Prac.RelationShips.Models.Employee", b =>
                {
                    b.Navigation("SystemDetail");
                });

            modelBuilder.Entity("EF_Prac.RelationShips.Models.OfficeFloor", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
